# Generated by Django 3.2.8 on 2021-11-06 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_seller_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller_session',
            old_name='seller_id',
            new_name='seller',
        ),
    ]
