# Generated by Django 3.2.8 on 2021-11-06 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0003_rename_seller_id_seller_session_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller_OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.CharField(max_length=50)),
                ('otp', models.CharField(max_length=10)),
                ('time_of_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='seller',
            name='email_id',
            field=models.CharField(default='random_testmail@gmail.com', max_length=50),
            preserve_default=False,
        ),
    ]
