# Generated by Django 3.2.8 on 2021-11-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0004_auto_20211107_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_otp',
            name='meta_data',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
