# Generated by Django 3.2.8 on 2021-11-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0005_seller_otp_meta_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='seller',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
