# Generated by Django 3.2.8 on 2021-11-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0007_alter_seller_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='contact_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='email_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
