# Generated by Django 3.2.8 on 2021-11-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='description',
        ),
        migrations.AddField(
            model_name='inventory',
            name='product_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
