# Generated by Django 3.2.8 on 2021-11-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20211108_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='product_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
