# Generated by Django 3.2.8 on 2021-11-06 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.CharField(max_length=50)),
                ('otp', models.CharField(max_length=10)),
                ('time_of_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='customer_session',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='order_details',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
