# Generated by Django 3.2.8 on 2021-11-06 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_admin_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.CharField(max_length=50)),
                ('otp', models.CharField(max_length=10)),
                ('time_of_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='admin_session',
            old_name='admin_id',
            new_name='admin',
        ),
    ]
