# Generated by Django 3.2.8 on 2021-11-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_admin_otp_meta_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='email_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
