# Generated by Django 3.2.8 on 2021-11-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0005_admin_email_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='admin',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
